# general
gpu_id: 0
use_gpu: True
state: INFO
reproducibility: True
data_path: 'dataset/'
checkpoint_dir: 'saved'
show_progress: True
save_dataset: False
save_dataloaders: False

# dataset
load_col:
    inter: [session_id, item_id]
    # item: [business_id]
MAX_ITEM_LIST_LENGTH: 50
USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: date

seq_len:
    item_id_list: 50

# Filtering
#val_interval: {'date': "[1546264800,1577714400]"}
filter_inter_by_user_or_item: True
user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

group_size: 25

perturb_eps: 0.05