field_separator: "\t"           # (str) Separator of different columns in atomic files.
seq_separator: " "              # (str) Separator inside the sequence features.
encoding: "utf-8"

USER_ID_FIELD: "user_id"
ITEM_ID_FIELD: "business_id"
LABEL_FIELD: ~
TIME_FIELD: "date"

load_col:
  inter: ["user_id", "business_id", "date"]

unload_col: ~

threshold: ~
rm_dup_inter: ~
val_interval: {'date': "[1546264800,1577714400]"}
filter_inter_by_user_or_item: True
user_inter_num_interval: "[5, inf)"
item_inter_num_interval: "[5, inf)"

alias_of_user_id: ~
alias_of_item_id: ~

group_size: 25

perturb_eps: 0.05

