field_separator: "\t"           # (str) Separator of different columns in atomic files.
seq_separator: " "              # (str) Separator inside the sequence features.
encoding: "utf-8"

USER_ID_FIELD: "user_id"
ITEM_ID_FIELD: "item_id"
LABEL_FIELD: ~
TIME_FIELD: "timestamp"

load_col:
  inter: ["user_id", "item_id", "timestamp"]

unload_col: ~

threshold: ~
rm_dup_inter: "first"
val_interval: ~
filter_inter_by_user_or_item: True
user_inter_num_interval: "[5, inf)"
item_inter_num_interval: "[5, inf)"

alias_of_user_id: ~
alias_of_item_id: ~

