field_separator: "\t"           # (str) Separator of different columns in atomic files.
seq_separator: " "              # (str) Separator inside the sequence features.
encoding: "utf-8"

load_col:
    inter: [user_id, item_id, rating, timestamp]
    item: [item_id, genre]
unload_col: ~

USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
LABEL_FIELD: ~
TIME_FIELD: timestamp
threshold: ~                    # {'rating': 4}

alias_of_user_id: ~
alias_of_item_id: ~
seq_len: ~

rm_dup_inter: "first"
val_interval: ~
filter_inter_by_user_or_item: True
user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

group_size: 25