# training settings
epochs: 300
seed: 42
train_batch_size: 1024
learner: adam
learning_rate: 0.001
eval_step: 1
stopping_step: 10
clip_grad_norm: ~
weight_decay: 0.0
train_neg_sample_args: ~

# evaluation settings
eval_args:
  split: { 'LS': 'valid_and_test' }
  group_by: user
  order: TO
  mode: full

repeatable: True
metrics: ["Hit","MRR","NDCG"]
topk: [1,3,5,10,20,50]
valid_metric: Hit@10
valid_metric_bigger: True
eval_batch_size: 1024
loss_decimal_place: 4
metric_decimal_place: 4
